language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kapp96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kapp96/docker-react npm run test -- --coverage

