language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kapp96/book -f Dockerfile.dev .

script:
  - docker run -e CI=true kapp96/book npm run test -- --coverage

