language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kapp96/docker2 -f Dockerfile.dev .

script:
  - docker run -e CI=true kapp96/docker1 npm run test -- --coverage

