language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t komal96/pen -f Dockerfile.dev .

script:
  - docker run -e CI=true komal96/pen npm run test -- --coverage

